{
  config,
  inputs,
  lib,
  ...
}:

let
  flakeConfig = config;
  emacs-tty = "emacsclient -t";
  inherit (config.local)
    default-font
    default-monospace-font
    default-serif-font
    email-addresses
    google-calendar-account
    username
    ;
  email-address-elisp = lib.concatMapAttrsStringSep "\n" (
    name: id: "    (${builtins.toJSON name} . ${builtins.toJSON id})"
  ) email-addresses;
  google-calendar-email-address = email-addresses.${google-calendar-account};
in
{
  config.local = {
    nixos.modules.host = { pkgs, ... }: {
      environment.systemPackages =
        let
          aspell = pkgs.aspellWithDicts (
            dicts: with dicts; [
              en
              en-computers
              en-science
            ]
          );
        in
        [ aspell ] ++ (with pkgs; [ languagetool ]);
    };

    home-manager.users.${username} = { osConfig, pkgs, ... }: {
      imports = [ inputs.doom-emacs.homeModule ];

      xdg.configFile."emacs-nix-constants.el".text = ''
        ;;; emacs-nix-constants.el --- Constants generated by Nix -*- lexical-binding: t; -*-

        ;;; Commentary:
        ;; This file exposes public Nix configuration to Emacs. Secret values must
        ;; remain in runtime-only files managed by Agenix.

        ;;; Code:

        (defconst nix-default-font ${builtins.toJSON default-font}
          "Default sans-serif font family configured by Nix.")

        (defconst nix-default-monospace-font ${builtins.toJSON default-monospace-font}
          "Default monospace font family configured by Nix.")

        (defconst nix-default-serif-font ${builtins.toJSON default-serif-font}
          "Default serif font family configured by Nix.")

        (defconst nix-desktop ${builtins.toJSON flakeConfig.local.desktop}
          "Complete desktop profile selected by Nix.")

        (defconst nix-email-addresses
          '(
        ${email-address-elisp}
            )
          "Email addresses keyed by their short Nix names.")

        (defconst nix-google-calendar-account ${builtins.toJSON google-calendar-email-address}
          "Google account used to authorize access to configured calendars.")

        (defconst nix-org-gcal-client-id-file ${builtins.toJSON osConfig.age.secrets.org-gcal-client-id.path}
          "Runtime file containing the Org-gcal OAuth client ID.")

        (defconst nix-org-gcal-client-secret-file ${builtins.toJSON osConfig.age.secrets.org-gcal-client-secret.path}
          "Runtime file containing the Org-gcal OAuth client secret.")

        (provide 'emacs-nix-constants)

        ;;; emacs-nix-constants.el ends here
      '';

      home = {
        sessionVariables = {
          EDITOR = emacs-tty;
          VISUAL = emacs-tty;
        };
        shellAliases = {
          vi = emacs-tty;
          vim = emacs-tty;
          nvim = emacs-tty;
        };
      };

      programs.doom-emacs = {
        enable = true;
        emacs = pkgs.emacs-pgtk;
        extraPackages = epkgs: [ epkgs.treesit-grammars.with-all-grammars ];
      };

      # EWM owns the only Emacs daemon in its desktop profile.
      services.emacs =
        if flakeConfig.local.desktop == "ewm" then
          { enable = false; }
        else
          {
            enable = true;
            startWithUserSession = true;
          };

      systemd.user.tmpfiles.rules = [
        "d %h/org 0700 - - -"
        "d %h/org/calendars 0700 - - -"
      ]
      ++ map (name: "f %h/org/calendars/${name}.org 0600 - - -") (builtins.attrNames email-addresses);
    };
  };
}
