{
  config,
  inputs,
  lib,
  ...
}:

let
  flakeConfig = config;
  inherit (flakeConfig.local) default-font keyboard username;

  ewmPackageFor =
    pkgs:
    let
      ewmPkgs = inputs.ewm.inputs.nixpkgs.legacyPackages.${pkgs.stdenv.hostPlatform.system};
      compatiblePkgs = pkgs // {
        inherit (ewmPkgs) libdisplay-info;
      };
    in
    pkgs.callPackage "${inputs.ewm}/nix/default.nix" {
      pkgs = compatiblePkgs;
      emacsPackage = pkgs.emacs-pgtk;
    };
in
{
  config = lib.mkIf (flakeConfig.local.desktop == "ewm") {
    local = {
      nixos.modules.host =
        { config, pkgs, ... }:
        let
          ewmPackage = ewmPackageFor pkgs;
        in
        {
          imports = [ inputs.ewm.nixosModules.default ];

          programs.ewm = {
            enable = true;
            package = ewmPackage;
            inherit ewmPackage;
            emacsPackage = config.home-manager.users.${username}.programs.doom-emacs.finalEmacsPackage;
            renderDevice = "/dev/dri/by-path/pci-0000:00:02.0-render";
            screencast.enable = true;
            withSkia = false;
          };

          security.pam.services.swaylock = { };

          systemd.user.services = {
            ewm = {
              conflicts = [ "emacs.service" ];
              overrideStrategy = "asDropin";
            };
            xdg-desktop-portal-gnome = {
              after = [ "ewm.service" ];
              overrideStrategy = "asDropin";
              requires = [ "ewm.service" ];
            };
          };
        };

      home-manager.users.${username} =
        { pkgs, ... }:
        let
          ewmPackage = ewmPackageFor pkgs;
          taskPackageArgs = {
            desktop = "ewm";
            inherit pkgs;
          };
          taskCapture = flakeConfig.local.taskwarrior.packages.taskCapture taskPackageArgs;
          taskDashboard = flakeConfig.local.taskwarrior.packages.taskDashboard taskPackageArgs;

          ewmDoomConfig = pkgs.writeText "ewm-doom-config.el" ''
            ;;; ewm-doom-config.el --- Doom integration for EWM -*- lexical-binding: t; -*-

            ;;; Commentary:
            ;; This file is generated by Nix and loaded only by the EWM desktop
            ;; profile.  The ordinary Hyprland and TTY Doom profiles do not see it.

            ;;; Code:

            (setq ewm-animations-enabled nil
                  ewm-cursor-auto-hide 5
                  ewm-cursor-hide-when-typing t
                  ewm-cursor-size 24
                  ewm-cursor-theme "BreezeX-RosePine-Linux"
                  ewm-focus-follows-mouse nil
                  ewm-input-config
                  '((keyboard
                     :repeat-delay 150
                     :repeat-rate 100
                     :xkb-layouts ${builtins.toJSON keyboard.layout}
                     :xkb-options ${builtins.toJSON keyboard.options}
                     :xkb-variants ${builtins.toJSON keyboard.variant})
                    (touchpad
                     :click-method "clickfinger"
                     :dwt t
                     :natural-scroll t
                     :tap nil))
                  ewm-mouse-follows-focus t
                  ewm-unfocused-alpha 0.8)

            (when (daemonp)
              (add-hook
               'after-make-frame-functions
               (defun nix-ewm-trigger-server-hooks-h (frame)
                 "Apply Doom's deferred graphical setup to EWM's first FRAME."
                 (when (display-graphic-p frame)
                   (remove-hook
                    'after-make-frame-functions
                    #'nix-ewm-trigger-server-hooks-h)
                   (with-selected-frame frame
                     (run-hooks 'server-after-make-frame-hook))))))

            (defun nix-ewm-close-selected-window ()
              "Close the selected EWM surface or kill the selected Emacs buffer."
              (interactive)
              (if-let ((surface-id (ewm-surface-buffer-p (window-buffer))))
                  (ewm-close surface-id)
                (kill-current-buffer)))

            (defun nix-ewm-refuse-daemon-restart-a (&rest _)
              "Reject restarting Emacs while it owns the graphical session."
              (user-error
               "Restarting Emacs ends EWM; save your work and log out instead"))

            (when (fboundp 'restart-emacs-service)
              (advice-add
               #'restart-emacs-service
               :override
               #'nix-ewm-refuse-daemon-restart-a))

            (after! ewm
              (map! :map ewm-mode-map
                    "s-SPC" #'ewm-launch-app
                    "s-b" (cmd! (start-process "zen-twilight" nil "zen-twilight"))
                    "s-c" (cmd! (start-process "task-capture" nil ${builtins.toJSON "${taskCapture}/bin/task-capture"}))
                    "s-d" (cmd! (start-process "legcord" nil "legcord"))
                    "s-e" #'ewm-frame-new
                    "s-f" #'ewm-toggle-fullscreen
                    "s-h" #'ewm-focus-left
                    "s-i" (cmd! (start-process "yazi" nil "wezterm" "start" "yazi"))
                    "s-j" #'ewm-focus-down
                    "s-k" #'ewm-focus-up
                    "s-l" #'ewm-focus-right
                    "s-m" (cmd! (start-process "spotify" nil "spotify"))
                    "s-n" (cmd! (start-process "logseq" nil "logseq"))
                    "s-o" (cmd! (start-process
                                  "nixos-terminal" nil
                                  "wezterm" "start"
                                  "--cwd=/etc/nixos"
                                  "sudo" "zsh" "-l"))
                    "s-p" (cmd! (start-process "btop" nil "wezterm" "start" "btop"))
                    "s-t" (cmd! (start-process "wezterm" nil "wezterm"))
                    "s-w" #'nix-ewm-close-selected-window
                    "s-y" (cmd! (start-process "task-dashboard" nil ${builtins.toJSON "${taskDashboard}/bin/task-dashboard"}))
                    "s-z" (cmd! (start-process "zulip" nil "zulip"))
                    "s-S-l" #'ewm-lock-session
                    "s-S-t" #'ewm-frame-new
                    "s-S-w" #'ewm-frame-close))

            (provide 'ewm-doom-config)

            ;;; ewm-doom-config.el ends here
          '';

          ewmDoomDir = pkgs.runCommand "doom-ewm" { } ''
            cp -R ${../doom} "$out"
            chmod -R u+w "$out"

            substituteInPlace "$out/init.el" \
              --replace-fail '(corfu +orderless)' ';;(corfu +orderless)' \
              --replace-fail '(vertico +childframe)' 'vertico' \
              --replace-fail '(syntax +childframe +flymake +icons)' '(syntax +flymake +icons)' \
              --replace-fail '       workspaces        ;' '       ;;workspaces      ;'

            cat >> "$out/config.el" <<'EOF'

            (load ${builtins.toJSON "${ewmDoomConfig}"} nil nil)
            EOF
          '';
        in
        {
          home.sessionVariables = {
            XCURSOR_SIZE = "24";
            XCURSOR_THEME = "BreezeX-RosePine-Linux";
          };

          programs = {
            doom-emacs = {
              doomDir = ewmDoomDir;
              extraPackages = _epkgs: [ ewmPackage ];
            };
            swaylock = {
              enable = true;
              settings = {
                color = "000000";
                font = default-font;
                show-failed-attempts = true;
              };
            };
          };

          services = {
            mako = {
              enable = true;
              settings = {
                anchor = "top-right";
                "background-color" = "#000000";
                "border-color" = "#ffffff";
                "border-radius" = 8;
                "default-timeout" = 5000;
                font = "${default-font} 11";
                layer = "overlay";
                margin = 8;
              };
            };
            polkit-gnome.enable = true;
            swayidle = {
              enable = true;
              events = {
                before-sleep = "${pkgs.swaylock}/bin/swaylock -f";
                lock = "${pkgs.swaylock}/bin/swaylock -f";
              };
            };
          };

          systemd.user.services.ewm-wallpaper = {
            Unit = {
              After = [ "graphical-session.target" ];
              Description = "EWM wallpaper";
              PartOf = [ "graphical-session.target" ];
            };
            Service = {
              ExecStart = "${pkgs.swaybg}/bin/swaybg -i ${inputs.desktop-background} -m fill";
              Restart = "on-failure";
              RestartSec = 1;
            };
            Install.WantedBy = [ "graphical-session.target" ];
          };
        };
    };
  };
}
